# 1. Portada

Proyecto final tips

Dataset: Tips

Integrantes: 
- Joan Manuel Rosario, 2024-0919
- Jabieni Fragoso, 2024-0893
- Mario Montes de Oca, 2024-0263

Fecha: 15 de marzo de 2026

# 2. Introdución y objetivos

Por qué eligieron el dataset: Elijimos este dataset para comprobar cuanto se le entregue de propina usualmente a un trabajador.

Qué desean explorar: Deseamos explorar la parte de como ha ido aumentando o disminuyendo la cantidad de tips con el pasar del tiempo.

Preguntas iniciales: 

1. ¿Cuántos registros (filas) tiene el dataset?

2. ¿Cuántas columnas o variables contiene el dataset?

3. ¿Cuáles son los nombres de las columnas del dataset?

# 3. Carga del Dataset y Exploración Inicial

Debe contener:
- Cargar el dataset con sns.load_dataset()
- head(), info(), describe()
- Variables numéricas vs categóricas
- Revisión de nulos
- Observaciones iniciales

In [14]:
#Completar

import seaborn as sns

TipsDataSet = sns.load_dataset("tips")

TipsDataSet.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [15]:
TipsDataSet.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [16]:
TipsDataSet.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [17]:
TipsDataSet.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

- El dataset contiene información sobre cuentas y propinas en un restaurante.

- Como se puede observar el dataset incluye variables relacionadas con el monto total de la cuenta, la propina, el sexo del cliente, si fuma o no, el día de la semana, el horario y el tamaño del grupo.

- Las variables total_bill y tip parecen ser las más importantes para analizar la relación entre cuenta y propina, ya que van de la mano una con otra.

- Las variables categóricas permiten comparar comportamientos entre días, horarios o tipos de clientes.

# 4. Limpieza de Datos

Nivel básico:
- Manejar nulos
- Corregir tipos de datos
- Quitar duplicados
- Ajustes simples de categorías

In [ ]:
#completar

# 5. Análisis Univariado – Distribuciones

Analizar al menos 3 variables usando al menos 2 de los siguientes gráficos:
- Histogramas
- KDE plots
- Boxplots
- Countplots

Con interpretación breve.

In [ ]:
#Completar

# 6. Análisis Bivariado – Relaciones
Al menos 3 relaciones usando al menos 3 de los siguientes gráficos:
-Scatterplot
- Lineplot
- Barplot
- Boxplot comparativo
- Heatmap de correlaciones (si aplica)

Cada gráfica debe incluir explicación.

In [ ]:
#Completar

# 7. Conclusiones Finales
Debe incluir:
- Patrones encontrados
- Relaciones más importantes
- Variables clave
- Posibles preguntas a investigar en el futuro

In [ ]:
#Completar, aqui puede ser que no se tenga que tirar codigo, solo conclusion.

# 8. Presentación del Notebook
Se evalúa:
- Orden del contenido
- Código limpio
- Comentarios claros
- Gráficos etiquetados
- Uso adecuado de Markdown